final:hw7.o circle.o rec.o tri.o

hw7.o:hw7.cpp\
	gcc -c hw7.cpp

circle.o:circle.cpp Shape.hpp\
	gcc -c circle.cpp

rec.o:rec.cpp Shape.hpp\
	gcc -c rec.cpp

tri.o:tri.cpp Shape.hpp\
	gcc -c rec.cpp

